version: '3'

services:
  web:
    hostname: web
    ports:
      - "80:80"
    volumes:
      - ./docker/default.dev.conf:/etc/nginx/conf.d/default.conf
      - ./:/usr/src/app
    depends_on:
      - php
  php:
    hostname: php
    environment:
      - YII_ENV_DEV=1
    volumes:
      - ./:/usr/src/app
