name: Notify and assign us

on:
  pull_request:
    branches:
      - master
      - feature/*
      - bugfix/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Assign us as reviewer
      uses: rowi1de/auto-assign-review-teams@v1.0.0
      with:
        repo-token: "{{ secrets.GITHUB_TOKEN }}"
        teams: unity
    - name: Notify us
      uses: aliencube/microsoft-teams-actions@v0.8.0
      with:
        webhook_uri: "{{ secrets.WEBHOOK_URI }}"
        title: "Api-Mock - Pull Request"
        text: "A new Pull-Request was created for the Api-Mock"
        actions: '[{ "@type": "OpenUri", "name": "Pull Request", "targets": [{ "os": "default", "uri": "https://github.com/surplex/api-mock/pulls" }] }]'
      
