name: Validate master

on:
  push:
    branches:
      - master
      - feature/*
      - bugfix/*
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup PHP with tools
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
    - name: Validate composer.json and composer.lock
      run: composer validate
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
    - name: prepare api tests
      run: bin/console migrate/up --interactive 0
    - name: Run unit tests
      run: bin/codecept run unit
    - name: Run api tests
      run: bin/codecept run api
